"""Section headings the tools recognise (the document stores them in ALL CAPS)."""
EN = ("SUMMARY", "PROFILE", "PROFESSIONAL EXPERIENCE", "EXPERIENCE", "SKILLS", "PROJECTS", "EDUCATION",
      "LANGUAGES", "CERTIFICATIONS", "PUBLICATIONS", "INTERESTS")
DE = ("KURZPROFIL", "PROFIL", "BERUFSERFAHRUNG", "KENNTNISSE", "PROJEKTE", "AUSBILDUNG", "SPRACHEN",
      "ZERTIFIKATE", "INTERESSEN")
ALL = set(EN) | set(DE)
# first body heading = end of the protected header zone
ANCHORS = ("SUMMARY", "PROFILE", "KURZPROFIL", "PROFIL", "PROFESSIONAL EXPERIENCE", "EXPERIENCE",
           "BERUFSERFAHRUNG", "KENNTNISSE", "SKILLS")
SUMMARY_KEYS = ("SUMMARY", "PROFILE", "KURZPROFIL", "PROFIL")
GERMAN_MARKERS = ("KURZPROFIL", "BERUFSERFAHRUNG", "KENNTNISSE", "AUSBILDUNG")
